version: "3"

services:
    ros_ai:
        image: fastsense/ros_ai:latest

        #environment:
            #- ROS_HOSTNAME=192.168.11.1
            #- ROS_MASTER_URI=http://localhost:11311
        volumes:
            - ../desktop_demo:/home/user/catkin_ws/src/
            - /dev/:/dev/
        privileged: true
        network_mode: "host"

        stdin_open: true
        tty: true
